### ISSUE TITLE
Avon (MS1) pre-deploy checklist

### ISSUE THREAD

**Issue by Gum-Joe** [Gum-Joe/isitweeka#31]
SITE CHECKLIST BEFORE DEPLOY:

- [x] Ensure everything for v1 is merged into this PR
- [x] Update events list for BOTH KECHB and KECHG as needed (KECHG needs a new list)
- [x] Remove alerts, or set the alert to something that makes sense
- [ ] Remove the "More coming soon" -> likely replace with a CTA
- [ ] Ensure site works both with and without cookies
- [ ] Validate the isitweeka text is good and all button work
- [ ] Validate site works both with and without cookies, and the tabs work and save preferences
